proxy_source:
    nz: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=nz&n=0"
    sa: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=sa&n=0"
    mz: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=mz&n=0"
    tw: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=tw&n=0"
    ve: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=ve&n=0" 
    kg: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=kg&n=0"
    pe: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=pe&n=0"
    uz: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=uz&n=0"
    mg: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=mg&n=0"
    np: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=np&n=0"
    pk: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=pk&n=0"
    ph: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=ph&n=0"
    vn: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=vn&n=0"
    mm: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=mm&n=0"
    th: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=th&n=0"
    my: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=my&n=0"
    id: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=id&n=0"
    tl: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=tl&n=0"
    kw: "http://tiqu.linksocket.com:81/abroad?num=100&type=1&pro=0&city=0&yys=0&port=1&flow=1&ts=0&ys=0&cs=0&lb=1&sb=0&pb=4&mr=0&regions=kw&n=0"
    cn: "http://ip.ipjldl.com/index.php/api/entry?method=proxyServer.hdtiqu_api_url&packid=0&fa=0&groupid=0&fetch_key=&time=102&qty=1&port=2&format=txt&ss=1&css=&dt=0&pro=&city=&usertype=4"
    hn: "http://120.79.85.144/index.php/api/entry?method=proxyServer.tiqu_api_url&packid=0&fa=0&dt=0&groupid=0&fetch_key=&qty=1&time=2&port=3&format=txt&ss=1&css=&dt=0&pro=%E6%B9%96%E5%8C%97%E7%9C%81&city=&usertype=6"
    
check_source:
    nz: "https://www.baidu.com/, https://www.qq.com/"
    sa: "https://www.baidu.com/, https://www.qq.com/"
    mz: "https://www.baidu.com/, https://www.qq.com/"
    tw: "https://www.baidu.com/, https://www.qq.com/"
    ve: "https://www.baidu.com/, https://www.qq.com/"
    kg: "https://www.baidu.com/, https://www.qq.com/"
    pe: "https://www.baidu.com/, https://www.qq.com/"
    uz: "https://www.baidu.com/, https://www.qq.com/"
    mg: "https://www.baidu.com/, https://www.qq.com/"
    np: "https://www.baidu.com/, https://www.qq.com/"
    pk: "https://www.baidu.com/, https://www.qq.com/"
    ph: "https://www.baidu.com/, https://www.qq.com/"
    vn: "https://www.baidu.com/, https://www.qq.com/"
    mm: "https://www.baidu.com/, https://www.qq.com/"
    th: "https://www.baidu.com/, https://www.qq.com/"
    my: "https://www.baidu.com/, https://www.qq.com/"
    id: "https://www.baidu.com/, https://www.qq.com/"
    tl: "https://www.baidu.com/, https://www.qq.com/"
    kw: "https://www.baidu.com/, https://www.qq.com/"
    cn: "https://www.baidu.com/, https://www.qq.com/"
    hn: "https://www.baidu.com/, https://www.qq.com/"
    
#check_wait_time: "3"
#min_port: "10001"
#max_port: "20500"
#max_request_ms: "700"
#
#squid:
#    config_path: "/etc/squid/squid.conf"